import './toggle';
// import './anchor';
import './parallax';
import './lazy-load';
import './slides';
import './menu-preview';
import './product-card';
import './components';
import './air-datepicker';
import './copy-link';